import json
import os
import httpx
from src.utils.logger import get_logger

logger = get_logger(__name__)


class UIDesignAgent:
    """Uses Claude API to generate beautiful, production-ready frontend UI."""

    def __init__(self):
        self.agent_name = "UIDesignAgent"
        self.api_key = os.getenv("ANTHROPIC_API_KEY", "")
        self.model = "claude-sonnet-4-20250514"
        self.api_url = "https://api.anthropic.com/v1/messages"
        logger.info("%s initialised.", self.agent_name)

    async def enhance_frontend(
        self,
        project_name: str,
        problem_statement: str,
        existing_frontend_files: list[dict],
        reference_context: str = "",
        tech_stack: str = "React TypeScript TailwindCSS",
    ) -> dict:
        """Take existing frontend files generated by Groq and enhance them
        with Claude's superior UI design capabilities.

        Returns enhanced files list with improved content.
        """
        def _priority(path: str) -> int:
            if path.endswith("App.tsx"):
                return 0
            if "/pages/" in path:
                return 1
            if "/layouts/" in path:
                return 2
            if "/components/" in path:
                return 3
            if path.endswith("index.css"):
                return 4
            if path.endswith("index.tsx"):
                return 5
            return 9

        ordered_files = sorted(
            existing_frontend_files,
            key=lambda f: (_priority(f.get("path", "")), f.get("path", "")),
        )
        context_files = ordered_files[:12]
        files_context = "\n\n".join([
            f"### {f['path']}\n{f['content'][:1600]}"
            for f in context_files
        ])
        file_index = "\n".join([f"- {f['path']}" for f in ordered_files])

        system_prompt = """You are an expert UI/UX engineer and React developer.

    Your job is to enhance the existing React frontend to be more polished and professional
    WITHOUT changing functionality, routes, or data flows.

    Rules:
    1. Return ONLY a valid JSON array of file objects: [{"path": str, "content": str}]
    2. Preserve the file structure and API contracts. Do NOT add/remove pages or routes.
    3. Use TailwindCSS for styling. No inline styles.
    4. Do NOT introduce new dependencies unless already present. If you must add one, update package.json.
    5. Keep all existing functionality intact — only improve layout, spacing, typography, and visual hierarchy.
    6. If a design reference is provided, align with it. Otherwise use a cohesive, modern light theme.
    7. Make it fully responsive for mobile, tablet, and desktop.
    8. Return ALL frontend files; if a file doesn't need changes, return it unchanged.
    9. No markdown fences in file content. No placeholders or truncation."""

        user_prompt = f"""Project: {project_name}
Description: {problem_statement}
{f"Design Reference: {reference_context}" if reference_context else ""}

Frontend file list (do not add/remove files):
{file_index}

Existing frontend files to enhance:
{files_context}

Enhance the UI while preserving structure and logic. Return ONLY the JSON array."""

        try:
            async with httpx.AsyncClient(timeout=120) as client:
                response = await client.post(
                    self.api_url,
                    headers={
                        "x-api-key": self.api_key,
                        "anthropic-version": "2023-06-01",
                        "content-type": "application/json",
                    },
                    json={
                        "model": self.model,
                        "max_tokens": 8000,
                        "messages": [
                            {"role": "user", "content": user_prompt}
                        ],
                        "system": system_prompt,
                    },
                )

                if response.status_code != 200:
                    logger.error("%s API error: %s", self.agent_name, response.text)
                    return {"status": "error", "files": existing_frontend_files}

                data = response.json()
                raw = data["content"][0]["text"]

                # Strip markdown fences some LLMs add despite instructions
                raw = raw.strip()
                if raw.startswith("```"):
                    raw = raw.split("```")[1]
                    if raw.startswith("json"):
                        raw = raw[4:]
                raw = raw.strip().rstrip("```").strip()

                enhanced_files = json.loads(raw)

                logger.info(
                    "%s enhanced %d frontend files",
                    self.agent_name, len(enhanced_files),
                )
                return {
                    "status": "success",
                    "files": enhanced_files,
                    "files_enhanced": len(enhanced_files),
                }

        except json.JSONDecodeError as e:
            logger.error("%s JSON parse error: %s", self.agent_name, e)
            return {"status": "error", "files": existing_frontend_files}
        except Exception as e:
            logger.exception("%s unexpected error: %s", self.agent_name, e)
            return {"status": "error", "files": existing_frontend_files}

    def is_frontend_file(self, path: str) -> bool:
        """Return True if the file path belongs to the frontend."""
        return (
            path.startswith("frontend/")
            or path.endswith(".tsx")
            or (path.endswith(".ts") and "backend" not in path)
            or (path.endswith(".css") and "backend" not in path)
            or ("src/" in path and "backend" not in path)
        )


ui_design_agent = UIDesignAgent()
