import json
import os
import httpx
from src.utils.logger import get_logger

logger = get_logger(__name__)


class UIDesignAgent:
    """Uses Claude API to generate beautiful, production-ready frontend UI."""

    def __init__(self):
        self.agent_name = "UIDesignAgent"
        self.api_key = os.getenv("ANTHROPIC_API_KEY", "")
        self.model = "claude-sonnet-4-20250514"
        self.api_url = "https://api.anthropic.com/v1/messages"
        logger.info("%s initialised.", self.agent_name)

    async def enhance_frontend(
        self,
        project_name: str,
        problem_statement: str,
        existing_frontend_files: list[dict],
        reference_context: str = "",
        tech_stack: str = "React TypeScript TailwindCSS",
    ) -> dict:
        """Take existing frontend files generated by Groq and enhance them
        with Claude's superior UI design capabilities.

        Returns enhanced files list with improved content.
        """
        files_context = "\n\n".join([
            f"### {f['path']}\n{f['content'][:2000]}"
            for f in existing_frontend_files[:8]
        ])

        system_prompt = """You are an elite UI/UX engineer and React developer with exceptional design taste.

Your job is to take existing React frontend code and completely redesign it to be:
- Visually stunning with modern design patterns
- Dark theme with glassmorphism effects
- Smooth animations using framer-motion
- Proper color system with gradients and accents
- Professional typography and spacing
- Fully responsive for mobile, tablet and desktop
- Production-ready code with no placeholders

Rules:
1. Return ONLY a valid JSON array of file objects: [{"path": str, "content": str}]
2. Include ALL frontend files — rewrite every single one
3. Use TailwindCSS for styling
4. Use framer-motion for animations
5. Use lucide-react for icons
6. Keep all the same functionality — only improve the UI
7. Make it look like a $10M startup's product
8. No markdown fences in file content
9. Complete file content — no truncation, no placeholders"""

        user_prompt = f"""Project: {project_name}
Description: {problem_statement}
{f"Design Reference: {reference_context}" if reference_context else ""}

Existing frontend files to redesign:
{files_context}

Redesign ALL frontend files with stunning UI. Keep same functionality, make it beautiful.
Return ONLY the JSON array."""

        try:
            async with httpx.AsyncClient(timeout=120) as client:
                response = await client.post(
                    self.api_url,
                    headers={
                        "x-api-key": self.api_key,
                        "anthropic-version": "2023-06-01",
                        "content-type": "application/json",
                    },
                    json={
                        "model": self.model,
                        "max_tokens": 8000,
                        "messages": [
                            {"role": "user", "content": user_prompt}
                        ],
                        "system": system_prompt,
                    },
                )

                if response.status_code != 200:
                    logger.error("%s API error: %s", self.agent_name, response.text)
                    return {"status": "error", "files": existing_frontend_files}

                data = response.json()
                raw = data["content"][0]["text"]

                # Strip markdown fences some LLMs add despite instructions
                raw = raw.strip()
                if raw.startswith("```"):
                    raw = raw.split("```")[1]
                    if raw.startswith("json"):
                        raw = raw[4:]
                raw = raw.strip().rstrip("```").strip()

                enhanced_files = json.loads(raw)

                logger.info(
                    "%s enhanced %d frontend files",
                    self.agent_name, len(enhanced_files),
                )
                return {
                    "status": "success",
                    "files": enhanced_files,
                    "files_enhanced": len(enhanced_files),
                }

        except json.JSONDecodeError as e:
            logger.error("%s JSON parse error: %s", self.agent_name, e)
            return {"status": "error", "files": existing_frontend_files}
        except Exception as e:
            logger.exception("%s unexpected error: %s", self.agent_name, e)
            return {"status": "error", "files": existing_frontend_files}

    def is_frontend_file(self, path: str) -> bool:
        """Return True if the file path belongs to the frontend."""
        return (
            path.startswith("frontend/")
            or path.endswith(".tsx")
            or (path.endswith(".ts") and "backend" not in path)
            or (path.endswith(".css") and "backend" not in path)
            or ("src/" in path and "backend" not in path)
        )


ui_design_agent = UIDesignAgent()
