"""Code executor tool for NexusFlow.

Runs Python snippets and shell commands in isolated subprocesses with a
configurable timeout. All output is captured and returned in a structured
dict so agents can inspect results without touching the terminal directly.

Usage::

    from src.tools.code_executor import code_executor

    result = code_executor.execute_python("print(1 + 1)")
    result = code_executor.execute_command("echo hello")
    result = code_executor.install_package("requests")

Security note:
    This tool executes arbitrary code. Only invoke it with content that has
    been reviewed or generated by a trusted agent in a controlled environment.
"""

import subprocess
import sys
import time

from src.utils.logger import get_logger

logger = get_logger(__name__)

_PYTHON = sys.executable


class CodeExecutorTool:
    """Subprocess-backed tool for executing Python code and shell commands.

    Each method spawns a new subprocess, enforces a wall-clock timeout, and
    captures stdout/stderr so the caller gets a complete picture of what ran
    and what it produced.

    Attributes:
        timeout: Maximum seconds a subprocess may run before being killed.
    """

    def __init__(self, timeout: int = 30) -> None:
        """Initialise the CodeExecutorTool.

        Args:
            timeout: Wall-clock seconds to allow each subprocess before it is
                terminated and a ``TimeoutExpired`` error is returned. Defaults
                to 30 seconds.
        """
        self.timeout = timeout
        logger.info("CodeExecutorTool initialised with timeout=%ds.", timeout)

    # ── Internal helper ───────────────────────────────────────────────────────

    def _run(self, args: list[str]) -> dict:
        """Run *args* as a subprocess and return a normalised result dict.

        Args:
            args: Command and argument list passed to :func:`subprocess.run`.

        Returns:
            ::

                {
                    "status":         "success" | "timeout" | "error",
                    "stdout":         str,
                    "stderr":         str,
                    "exit_code":      int | None,
                    "execution_time": float,   # wall-clock seconds
                }
        """
        start = time.monotonic()
        try:
            proc = subprocess.run(
                args,
                capture_output=True,
                text=True,
                timeout=self.timeout,
            )
            elapsed = time.monotonic() - start
            status = "success" if proc.returncode == 0 else "error"
            return {
                "status": status,
                "stdout": proc.stdout,
                "stderr": proc.stderr,
                "exit_code": proc.returncode,
                "execution_time": round(elapsed, 4),
            }
        except subprocess.TimeoutExpired:
            elapsed = time.monotonic() - start
            logger.warning("Subprocess timed out after %.2fs: %s", elapsed, args)
            return {
                "status": "timeout",
                "stdout": "",
                "stderr": f"Process exceeded timeout of {self.timeout}s.",
                "exit_code": None,
                "execution_time": round(elapsed, 4),
            }
        except Exception as exc:
            elapsed = time.monotonic() - start
            logger.exception("Subprocess execution failed: %s", exc)
            return {
                "status": "error",
                "stdout": "",
                "stderr": str(exc),
                "exit_code": None,
                "execution_time": round(elapsed, 4),
            }

    # ── Public methods ────────────────────────────────────────────────────────

    def execute_python(self, code: str) -> dict:
        """Execute a Python code string in an isolated subprocess.

        The code is passed via ``-c`` so no temporary files are created.
        stdout and stderr are captured separately.

        Args:
            code: Valid Python source code to execute.

        Returns:
            ::

                {
                    "status":         "success" | "timeout" | "error",
                    "stdout":         str,   # everything written to stdout
                    "stderr":         str,   # everything written to stderr
                    "exit_code":      int | None,
                    "execution_time": float,
                }

        Example::

            result = code_executor.execute_python("print(2 ** 10)")
            # result["stdout"] == "1024\\n"
        """
        logger.info("Executing Python code (timeout=%ds).", self.timeout)
        result = self._run([_PYTHON, "-c", code])
        logger.info(
            "Python execution finished — status=%s exit_code=%s time=%.4fs.",
            result["status"], result["exit_code"], result["execution_time"],
        )
        return result

    def execute_command(self, command: str) -> dict:
        """Execute a shell command string in an isolated subprocess.

        The command is split on whitespace and executed directly (no shell
        interpolation) to reduce injection risk. For commands that require
        shell features (pipes, redirects) the caller must pass
        ``shell=True`` — this method does not support that by design.

        Args:
            command: Shell command to run, e.g. ``"git status"`` or
                ``"ls -la /tmp"``.

        Returns:
            ::

                {
                    "status":         "success" | "timeout" | "error",
                    "stdout":         str,
                    "stderr":         str,
                    "exit_code":      int | None,
                    "execution_time": float,
                }
        """
        logger.info("Executing command: %r (timeout=%ds).", command, self.timeout)
        args = command.split()
        result = self._run(args)
        logger.info(
            "Command finished — status=%s exit_code=%s time=%.4fs.",
            result["status"], result["exit_code"], result["execution_time"],
        )
        return result

    def install_package(self, package_name: str) -> dict:
        """Install a PyPI package into the current Python environment via pip.

        Args:
            package_name: Package name (optionally with version specifier) as
                you would pass to ``pip install``, e.g. ``"requests"`` or
                ``"httpx==0.28.1"``.

        Returns:
            ::

                {
                    "status":  "success" | "timeout" | "error",
                    "package": str,   # the original package_name argument
                    "message": str,   # human-readable outcome
                    "stdout":  str,
                    "stderr":  str,
                }
        """
        logger.info("Installing package: %r", package_name)
        result = self._run([_PYTHON, "-m", "pip", "install", package_name])
        if result["status"] == "success":
            message = f"Package '{package_name}' installed successfully."
        elif result["status"] == "timeout":
            message = f"pip install '{package_name}' timed out after {self.timeout}s."
        else:
            message = f"Failed to install package '{package_name}'."

        logger.info(
            "install_package '%s' — status=%s time=%.4fs.",
            package_name, result["status"], result["execution_time"],
        )
        return {
            "status": result["status"],
            "package": package_name,
            "message": message,
            "stdout": result["stdout"],
            "stderr": result["stderr"],
        }


# Module-level singleton — import this directly instead of instantiating CodeExecutorTool yourself.
code_executor = CodeExecutorTool()
